plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "db/cache_schema.rb"
    - "db/queue_schema.rb"
    - "db/cable_schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "config/environments/**/*"
    - "config/initializers/devise.rb"
    - "config/locales/**/*.yml"
    - "test/**/*"

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"
    - "config/initializers/content_security_policy.rb"
    - "db/seeds.rb"

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Rails/FindBy:
  Enabled: true

Rails/SaveBang:
  Enabled: true

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

RSpec/NamedSubject:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - "spec/**/*"
    - "db/seeds.rb"
    - "app/services/workflows/evaluate_rules.rb"

Naming/PredicateMethod:
  Exclude:
    - "app/services/workflows/evaluate_rules.rb"

Layout/HashAlignment:
  Enabled: false
