FROM ruby:3.4-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      libpq-dev \
      nodejs \
      npm \
      curl \
      git && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g n && n 20

WORKDIR /rails

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["bin/dev"]